services:
  - type: web
    name: ntv-attendance
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: N8N_FETCH_DEPARTMENT_URL
        sync: false
      - key: N8N_UPDATE_ATTENDANCE_URL
        sync: false
