/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AttendanceRouteImport } from './routes/attendance'

const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/attendance': typeof AttendanceRoute
}
export interface FileRoutesByTo {
  '/attendance': typeof AttendanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/attendance': typeof AttendanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/attendance'
  fileRoutesByTo: FileRoutesByTo
  to: '/attendance'
  id: '__root__' | '/attendance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AttendanceRoute: typeof AttendanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AttendanceRoute: AttendanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
